### PR TITLE
[oneplus3] fix incorrect partition for userdata

### PR DESCRIPTION
**Pull request by adeen-s**
userdata lies on sda15 and not on sde15

### CODE REVIEW

**Comment by Nokius** [comment]
@adeen-s can u please add a list of all mount points to the comment  😄 

~~~~
ls -la /dev/block*
~~~~
in Recovery 

Thanks

**Comment by Nokius** [comment]
~~~~
drwxr-xr-x    3 root     root          1860 Nov 14  1970 .
drwxr-xr-x   10 root     root          2920 Nov 14  1970 ..
lrwxrwxrwx    1 root     root            36 Nov 14  1970 bootdevice -> /dev/block/platform/soc/624000.ufshc
brw-------    1 root     root      254,   0 Nov 14  1970 dm-0
brw-------    1 root     root        7,   0 Nov 14  1970 loop0
brw-------    1 root     root        7,   1 Nov 14  1970 loop1
brw-------    1 root     root        7,   2 Nov 14  1970 loop2
brw-------    1 root     root        7,   3 Nov 14  1970 loop3
brw-------    1 root     root        7,   4 Nov 14  1970 loop4
brw-------    1 root     root        7,   5 Nov 14  1970 loop5
brw-------    1 root     root        7,   6 Nov 14  1970 loop6
brw-------    1 root     root        7,   7 Nov 14  1970 loop7
drwxr-xr-x    3 root     root            60 Nov 14  1970 platform
brw-------    1 root     root        1,   0 Nov 14  1970 ram0
brw-------    1 root     root        1,   1 Nov 14  1970 ram1
brw-------    1 root     root        1,  10 Nov 14  1970 ram10
brw-------    1 root     root        1,  11 Nov 14  1970 ram11
brw-------    1 root     root        1,  12 Nov 14  1970 ram12
brw-------    1 root     root        1,  13 Nov 14  1970 ram13
brw-------    1 root     root        1,  14 Nov 14  1970 ram14
brw-------    1 root     root        1,  15 Nov 14  1970 ram15
brw-------    1 root     root        1,   2 Nov 14  1970 ram2
brw-------    1 root     root        1,   3 Nov 14  1970 ram3
brw-------    1 root     root        1,   4 Nov 14  1970 ram4
brw-------    1 root     root        1,   5 Nov 14  1970 ram5
brw-------    1 root     root        1,   6 Nov 14  1970 ram6
brw-------    1 root     root        1,   7 Nov 14  1970 ram7
brw-------    1 root     root        1,   8 Nov 14  1970 ram8
brw-------    1 root     root        1,   9 Nov 14  1970 ram9
brw-------    1 root     root        8,   0 Nov 14  1970 sda
brw-------    1 root     root        8,   1 Nov 14  1970 sda1
brw-------    1 root     root        8,  10 Nov 14  1970 sda10
brw-------    1 root     root        8,  11 Nov 14  1970 sda11
brw-------    1 root     root        8,  12 Nov 14  1970 sda12
brw-------    1 root     root        8,  13 Nov 14  1970 sda13
brw-------    1 root     root        8,  14 Nov 14  1970 sda14
brw-------    1 root     root        8,  15 Nov 14  1970 sda15
brw-------    1 root     root        8,   2 Nov 14  1970 sda2
brw-------    1 root     root        8,   3 Nov 14  1970 sda3
brw-------    1 root     root        8,   4 Nov 14  1970 sda4
brw-------    1 root     root        8,   5 Nov 14  1970 sda5
brw-------    1 root     root        8,   6 Nov 14  1970 sda6
brw-------    1 root     root        8,   7 Nov 14  1970 sda7
brw-------    1 root     root        8,   8 Nov 14  1970 sda8
brw-------    1 root     root        8,   9 Nov 14  1970 sda9
brw-------    1 root     root        8,  16 Nov 14  1970 sdb
brw-------    1 root     root        8,  17 Nov 14  1970 sdb1
brw-------    1 root     root        8,  32 Nov 14  1970 sdc
brw-------    1 root     root        8,  33 Nov 14  1970 sdc1
brw-------    1 root     root        8,  48 Nov 14  1970 sdd
brw-------    1 root     root        8,  49 Nov 14  1970 sdd1
brw-------    1 root     root        8,  50 Nov 14  1970 sdd2
brw-------    1 root     root        8,  51 Nov 14  1970 sdd3
brw-------    1 root     root        8,  64 Nov 14  1970 sde
brw-------    1 root     root        8,  65 Nov 14  1970 sde1
brw-------    1 root     root        8,  74 Nov 14  1970 sde10
brw-------    1 root     root        8,  75 Nov 14  1970 sde11
brw-------    1 root     root        8,  76 Nov 14  1970 sde12
brw-------    1 root     root        8,  77 Nov 14  1970 sde13
brw-------    1 root     root        8,  78 Nov 14  1970 sde14
brw-------    1 root     root        8,  79 Nov 14  1970 sde15
brw-------    1 root     root      259,   0 Nov 14  1970 sde16
brw-------    1 root     root      259,   1 Nov 14  1970 sde17
brw-------    1 root     root      259,   2 Nov 14  1970 sde18
brw-------    1 root     root      259,   3 Nov 14  1970 sde19
brw-------    1 root     root        8,  66 Nov 14  1970 sde2
brw-------    1 root     root      259,   4 Nov 14  1970 sde20
brw-------    1 root     root      259,   5 Nov 14  1970 sde21
brw-------    1 root     root      259,   6 Nov 14  1970 sde22
brw-------    1 root     root      259,   7 Nov 14  1970 sde23
brw-------    1 root     root      259,   8 Nov 14  1970 sde24
brw-------    1 root     root      259,   9 Nov 14  1970 sde25
brw-------    1 root     root      259,  10 Nov 14  1970 sde26
brw-------    1 root     root      259,  11 Nov 14  1970 sde27
brw-------    1 root     root      259,  12 Nov 14  1970 sde28
brw-------    1 root     root      259,  13 Nov 14  1970 sde29
brw-------    1 root     root        8,  67 Nov 14  1970 sde3
brw-------    1 root     root      259,  14 Nov 14  1970 sde30
brw-------    1 root     root      259,  15 Nov 14  1970 sde31
brw-------    1 root     root      259,  16 Nov 14  1970 sde32
brw-------    1 root     root      259,  17 Nov 14  1970 sde33
brw-------    1 root     root      259,  18 Nov 14  1970 sde34
brw-------    1 root     root        8,  68 Nov 14  1970 sde4
brw-------    1 root     root        8,  69 Nov 14  1970 sde5
brw-------    1 root     root        8,  70 Nov 14  1970 sde6
brw-------    1 root     root        8,  71 Nov 14  1970 sde7
brw-------    1 root     root        8,  72 Nov 14  1970 sde8
brw-------    1 root     root        8,  73 Nov 14  1970 sde9
brw-------    1 root     root        8,  80 Nov 14  1970 sdf
brw-------    1 root     root        8,  81 Nov 14  1970 sdf1
brw-------    1 root     root        8,  82 Nov 14  1970 sdf2
brw-------    1 root     root        8,  83 Nov 14  1970 sdf3
brw-------    1 root     root        8,  84 Nov 14  1970 sdf4
~~~~~

**Comment by adeen-s** [comment]
~~~~
OnePlus3:/dev/block/platform/soc/624000.ufshc/by-name # ls -la
total 0
drwxr-xr-x    2 root     root          1200 Aug 13  1970 .
drwxr-xr-x    4 root     root          1360 Aug 13  1970 ..
lrwxrwxrwx    1 root     root            16 Aug 13  1970 LOGO -> /dev/block/sde17
lrwxrwxrwx    1 root     root            16 Aug 13  1970 aboot -> /dev/block/sde15
lrwxrwxrwx    1 root     root            16 Aug 13  1970 abootbak -> /dev/block/sde16
lrwxrwxrwx    1 root     root            16 Aug 13  1970 apdp -> /dev/block/sde30
lrwxrwxrwx    1 root     root            16 Aug 13  1970 bluetooth -> /dev/block/sde23
lrwxrwxrwx    1 root     root            16 Aug 13  1970 boot -> /dev/block/sde18
lrwxrwxrwx    1 root     root            16 Aug 13  1970 boot_aging -> /dev/block/sde19
lrwxrwxrwx    1 root     root            15 Aug 13  1970 cache -> /dev/block/sda3
lrwxrwxrwx    1 root     root            15 Aug 13  1970 cdt -> /dev/block/sdd2
lrwxrwxrwx    1 root     root            16 Aug 13  1970 cmnlib -> /dev/block/sde26
lrwxrwxrwx    1 root     root            16 Aug 13  1970 cmnlib64 -> /dev/block/sde28
lrwxrwxrwx    1 root     root            16 Aug 13  1970 cmnlib64bak -> /dev/block/sde29
lrwxrwxrwx    1 root     root            16 Aug 13  1970 cmnlibbak -> /dev/block/sde27
lrwxrwxrwx    1 root     root            16 Aug 13  1970 config -> /dev/block/sda14
lrwxrwxrwx    1 root     root            15 Aug 13  1970 ddr -> /dev/block/sdd3
lrwxrwxrwx    1 root     root            15 Aug 13  1970 devcfg -> /dev/block/sda6
lrwxrwxrwx    1 root     root            15 Aug 13  1970 devcfgbak -> /dev/block/sda7
lrwxrwxrwx    1 root     root            16 Aug 13  1970 devinfo -> /dev/block/sde22
lrwxrwxrwx    1 root     root            16 Aug 13  1970 dip -> /dev/block/sde13
lrwxrwxrwx    1 root     root            16 Aug 13  1970 dpo -> /dev/block/sde32
lrwxrwxrwx    1 root     root            16 Aug 13  1970 dsp -> /dev/block/sde12
lrwxrwxrwx    1 root     root            15 Aug 13  1970 frp -> /dev/block/sda8
lrwxrwxrwx    1 root     root            15 Aug 13  1970 fsc -> /dev/block/sdf3
lrwxrwxrwx    1 root     root            15 Aug 13  1970 fsg -> /dev/block/sde7
lrwxrwxrwx    1 root     root            15 Aug 13  1970 hyp -> /dev/block/sde5
lrwxrwxrwx    1 root     root            15 Aug 13  1970 hypbak -> /dev/block/sde6
lrwxrwxrwx    1 root     root            16 Aug 13  1970 keymaster -> /dev/block/sde24
lrwxrwxrwx    1 root     root            16 Aug 13  1970 keymasterbak -> /dev/block/sde25
lrwxrwxrwx    1 root     root            15 Aug 13  1970 keystore -> /dev/block/sda5
lrwxrwxrwx    1 root     root            15 Aug 13  1970 md5 -> /dev/block/sdf4
lrwxrwxrwx    1 root     root            16 Aug 13  1970 mdtp -> /dev/block/sde14
lrwxrwxrwx    1 root     root            15 Aug 13  1970 misc -> /dev/block/sda4
lrwxrwxrwx    1 root     root            16 Aug 13  1970 modem -> /dev/block/sde11
lrwxrwxrwx    1 root     root            15 Aug 13  1970 modemst1 -> /dev/block/sdf1
lrwxrwxrwx    1 root     root            15 Aug 13  1970 modemst2 -> /dev/block/sdf2
lrwxrwxrwx    1 root     root            16 Aug 13  1970 msadp -> /dev/block/sde31
lrwxrwxrwx    1 root     root            15 Aug 13  1970 oem_dycnvbk -> /dev/block/sda9
lrwxrwxrwx    1 root     root            16 Aug 13  1970 oem_stanvbk -> /dev/block/sda10
lrwxrwxrwx    1 root     root            16 Aug 13  1970 param -> /dev/block/sda11
lrwxrwxrwx    1 root     root            15 Aug 13  1970 persist -> /dev/block/sda2
lrwxrwxrwx    1 root     root            15 Aug 13  1970 pmic -> /dev/block/sde9
lrwxrwxrwx    1 root     root            16 Aug 13  1970 pmicbak -> /dev/block/sde10
lrwxrwxrwx    1 root     root            16 Aug 13  1970 recovery -> /dev/block/sde21
lrwxrwxrwx    1 root     root            15 Aug 13  1970 reserve -> /dev/block/sdd1
lrwxrwxrwx    1 root     root            16 Aug 13  1970 reserve1 -> /dev/block/sda12
lrwxrwxrwx    1 root     root            16 Aug 13  1970 reserve2 -> /dev/block/sda13
lrwxrwxrwx    1 root     root            15 Aug 13  1970 rpm -> /dev/block/sde1
lrwxrwxrwx    1 root     root            15 Aug 13  1970 rpmbak -> /dev/block/sde2
lrwxrwxrwx    1 root     root            15 Aug 13  1970 sec -> /dev/block/sde8
lrwxrwxrwx    1 root     root            16 Aug 13  1970 splash -> /dev/block/sde33
lrwxrwxrwx    1 root     root            15 Aug 13  1970 ssd -> /dev/block/sda1
lrwxrwxrwx    1 root     root            16 Aug 13  1970 sti -> /dev/block/sde34
lrwxrwxrwx    1 root     root            16 Aug 13  1970 system -> /dev/block/sde20
lrwxrwxrwx    1 root     root            15 Aug 13  1970 tz -> /dev/block/sde3
lrwxrwxrwx    1 root     root            15 Aug 13  1970 tzbak -> /dev/block/sde4
lrwxrwxrwx    1 root     root            16 Aug 13  1970 userdata -> /dev/block/sda15
lrwxrwxrwx    1 root     root            15 Aug 13  1970 xbl -> /dev/block/sdb1
lrwxrwxrwx    1 root     root            15 Aug 13  1970 xblbak -> /dev/block/sdc1
~~~~

**Comment by Nokius** [comment]
Thanks

**Pull request merged**
